// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDORNGQYCufXNw14X_Y-ZZkloL5IgfKsf4',
    appId: '1:769019382476:web:6fb030a363f0adbced1069',
    messagingSenderId: '769019382476',
    projectId: 'as-dsm-37675',
    authDomain: 'as-dsm-37675.firebaseapp.com',
    storageBucket: 'as-dsm-37675.firebasestorage.app',
    measurementId: 'G-E1FCKCBDM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl7cRsmM9Ro2fTJKJquKYlgm47YiR3MT4',
    appId: '1:769019382476:android:99d8f8ed8aa42358ed1069',
    messagingSenderId: '769019382476',
    projectId: 'as-dsm-37675',
    storageBucket: 'as-dsm-37675.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcxy-2QaY5KVButZ93foqYdIVnvTzD17o',
    appId: '1:769019382476:ios:663f172e574e5f86ed1069',
    messagingSenderId: '769019382476',
    projectId: 'as-dsm-37675',
    storageBucket: 'as-dsm-37675.firebasestorage.app',
    iosBundleId: 'com.example.ap2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcxy-2QaY5KVButZ93foqYdIVnvTzD17o',
    appId: '1:769019382476:ios:663f172e574e5f86ed1069',
    messagingSenderId: '769019382476',
    projectId: 'as-dsm-37675',
    storageBucket: 'as-dsm-37675.firebasestorage.app',
    iosBundleId: 'com.example.ap2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDORNGQYCufXNw14X_Y-ZZkloL5IgfKsf4',
    appId: '1:769019382476:web:238974cc90b296f1ed1069',
    messagingSenderId: '769019382476',
    projectId: 'as-dsm-37675',
    authDomain: 'as-dsm-37675.firebaseapp.com',
    storageBucket: 'as-dsm-37675.firebasestorage.app',
    measurementId: 'G-PE3SR1ZFJQ',
  );
}
